#!/bin/sh

#exec /usr/bin/xscreensaver -no-splash &
#feh --bg-scale /usr/share/archlinux/wallpaper/archlinux-simplyblack.png
synclient TouchpadOff=1
xsetroot -cursor_name left_ptr
#xrdb -merge ~/.Xresources
xbindkeys
#exec xmonad
exec i3
